profiles:
  development:
    show_drafts: false
    cook: microwave
    base_url: http://localhost:4242
  production:
    show_drafts: true
    cook: oven
    asciidoctor:
      :eruby: erb
      :attributes:
        imagesdir: /img
  staging:
    compass_line_comments: off
    compass_output_style: :compact
    base_url: http://stage.example.com

title: Awestruction!

asciidoctor:
  :safe: 0
  :eruby: erubis
  :attributes:
    imagesdir: /assets/images
    idprefix: ''
