profiles:
  development:
    show_drafts: false
    cook: microwave
  production:
    show_drafts: true
    cook: oven
    asciidoctor:
      :eruby: erb
      :attributes:
        imagesdir: /img
  staging:
    compass_line_comments: off
    compass_output_style: :compact

title: Awestruction!

asciidoctor:
  :safe: 0
  :eruby: erubis
  :attributes:
    imagesdir: /assets/images
    idprefix: ''
