
profiles:
  development:
    cook: microwave
  production:
    cook: oven
  staging:
    compass_line_comments: off

title: Awestruction!

asciidoctor:
  default:
    :attributes:
      backend: html4
