
profiles:
  development:
    cook: microwave
  production:
    cook: oven
  staging:
    compass_line_comments: off
    compass_output_style: :compact

title: Awestruction!

asciidoctor:
  :attributes:
    backend: html4
